name: check-and-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-and-test:
    if: false  # disabled: no runner registered
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: build
        run: make build
      - name: security-check
        run: make security-check
